language: python
dist: xenial
python:
  - "3.5"
  - "3.6"
  - "3.7"
  - "3.7-dev"
  - "3.8-dev"
  - "nightly"
  - "pypy3"

install:
- pip install -U setuptools
- virtualenv --version
- easy_install --version
- pip --version
script:
- pip install -r requirements.txt
- pip install .
deploy:
  provider: pypi
  on:
    branch: master
  distributions: sdist bdist_wheel
  skip_existing: true
  user: iPhosgen
  password:
    secure: hv/yxTSl7wEoORfI2kaIr+nDO0bCGiQu3jBSVkvWoR4+Q3s2poct7tSir/ufyPuBUr7k4qKKW7IPXhPi1SsoIu+GLv+PNlCuEFR74TEXmDfBiHqzpbfwuJwurB764Dy6Qv8Xfs7XK5tft5btXZxwbk6kB1DRFhqcPFd9T9jfVrkG4HmDIMjA4bRaFwjpBwm3wM+uWRAPswMFgNvJH7VNn0jd5/kw01NJLHx++tmA6W3x0s52uGq+mbYBuK+HQLF6+lR5ApYWMoti22J3clIh9ys6dn8kHzzdWl6khC1m+32JrUukVsnPhCwvCunw18Al/aMR5g5znYXw5GUdG097nLNjxWHNz2yJ0RWe0lei//TTNCZJtZ2RV2e48X1X5qUpq/BCXcYPLmFe9KnoNgWXSHODU5vzM6iML75pVBGQxywDuKQbjcK2jY7ESqqTdRs75nlq2cWc/S3Np/y+8DLVMnbLUTK+gtDpIxaoHOYp9O1c0r/yoCem/jwGFORGn8dJVT567fP4BAYdPi+klJZ01kf1FPFHbZZEyYWdvEvtcH4ogz9XB5VP3gThaQDHPbPMSgNt1opMCWKrwx6w0u+KM8ElnuJkOE5Ck9ifme8kviyJgh4qy81V2LtQacPViIGDNDPcwtGkdlyH+P1wE1LMvePVJRxj4KMdaDcFFe/NKAE=
notifications:
  email:
    on_success: never
    on_failure: always
