language: python
dist: xenial
python:
  - "3.5"
  - "3.6"
  - "3.7"
  - "3.7-dev"
  - "3.8-dev"
  - "nightly"
  - "pypy3"

install:
- pip install -U setuptools
- virtualenv --version
- easy_install --version
- pip --version
script:
- pip install -r requirements.txt
- pip install .
deploy:
  provider: pypi
  user: "iPhosgen"
  password:
    secure: oVI4Z348/2mn6g8TdWqzCAjZUOT6Qz117qcRaa1mUp2ivYxac78pMnMMer7qmCeoJqg2sr9L8YAt3e4iOJDi0Lhzd6c729ulOSvyhDcfjTWmtPqG0PJDuIXyQ6fxPtWe3iLVeYSe0zDx9XWF4deL4rGJidI4N/iofG/DY4pBe0xqr33uh97jvlMAt9XxrfD09f76c6huufl5m0UbAD96upZjuJgow1tzg9Kf59JLXRoht1OTKwL3nlvoWOkHsc6t7Xv0duLKSyz8H2jfLXYOoCTgODnCWk0pG97vcIR9P5mw/OAjFxvJD2ZjIDysBrREYTLcHhEv4dYpDZs5DneYToz7xCkRnEC/OMxMl76f5tmMRGnFIDOENqnRXswD4jetpzs0pEvJonnYncMWDbs6hNDB1zl9XdYIUbPWYQa2w4OXQpKkldOOXJ4yd975wO1xGf0wZRh4nQSjC2lcxGHSFO+IagCaWP/E189pmViWnqHVe4lAGoUUTpi/sJ3FGGYdHyKWTJ74t6ounRUBo2NwnFZ7jUJur9KW1OoxFj9POuZJs+1oC6YrwOAzBAiFgRgbp55kf+7y6SoXnkkG4wXNMvFAgw3dviEpexqXuhHyCtYy5Bg2if1DhrHsHotTHh8Zf6X1aM1yoDfRQ6+0tgt95ZOvPG+nYyJztKs/nQWvpw4=
notifications:
  email:
    on_success: never
    on_failure: always